<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc\NextAddressRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>walletrpc.NextAddressRequest.Kind</code>
 */
class Kind
{
    /**
     * Generated from protobuf enum <code>BIP0044_EXTERNAL = 0;</code>
     */
    const BIP0044_EXTERNAL = 0;
    /**
     * Generated from protobuf enum <code>BIP0044_INTERNAL = 1;</code>
     */
    const BIP0044_INTERNAL = 1;

    private static $valueToName = [
        self::BIP0044_EXTERNAL => 'BIP0044_EXTERNAL',
        self::BIP0044_INTERNAL => 'BIP0044_INTERNAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Kind::class, \Walletrpc\NextAddressRequest_Kind::class);

