<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc\ChangePassphraseRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>walletrpc.ChangePassphraseRequest.Key</code>
 */
class Key
{
    /**
     * Generated from protobuf enum <code>PRIVATE = 0;</code>
     */
    const PBPRIVATE = 0;
    /**
     * Generated from protobuf enum <code>PUBLIC = 1;</code>
     */
    const PBPUBLIC = 1;

    private static $valueToName = [
        self::PBPRIVATE => 'PBPRIVATE',
        self::PBPUBLIC => 'PBPUBLIC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Key::class, \Walletrpc\ChangePassphraseRequest_Key::class);

