<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\AccountsResponse\Account instead.
     * @deprecated
     */
    class AccountsResponse_Account {}
}
class_exists(AccountsResponse\Account::class);
@trigger_error('Walletrpc\AccountsResponse_Account is deprecated and will be removed in the next major release. Use Walletrpc\AccountsResponse\Account instead', E_USER_DEPRECATED);

