<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.BalanceRequest</code>
 */
class BalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 account_number = 1;</code>
     */
    protected $account_number = 0;
    /**
     * Generated from protobuf field <code>int32 required_confirmations = 2;</code>
     */
    protected $required_confirmations = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $account_number
     *     @type int $required_confirmations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 account_number = 1;</code>
     * @return int
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>uint32 account_number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->account_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 2;</code>
     * @return int
     */
    public function getRequiredConfirmations()
    {
        return $this->required_confirmations;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequiredConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->required_confirmations = $var;

        return $this;
    }

}

