<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.BalanceResponse</code>
 */
class BalanceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>int64 spendable = 2;</code>
     */
    protected $spendable = 0;
    /**
     * Generated from protobuf field <code>int64 immature_reward = 3;</code>
     */
    protected $immature_reward = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total
     *     @type int|string $spendable
     *     @type int|string $immature_reward
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 spendable = 2;</code>
     * @return int|string
     */
    public function getSpendable()
    {
        return $this->spendable;
    }

    /**
     * Generated from protobuf field <code>int64 spendable = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSpendable($var)
    {
        GPBUtil::checkInt64($var);
        $this->spendable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 immature_reward = 3;</code>
     * @return int|string
     */
    public function getImmatureReward()
    {
        return $this->immature_reward;
    }

    /**
     * Generated from protobuf field <code>int64 immature_reward = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setImmatureReward($var)
    {
        GPBUtil::checkInt64($var);
        $this->immature_reward = $var;

        return $this;
    }

}

