<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\ChangePassphraseRequest\Key instead.
     * @deprecated
     */
    class ChangePassphraseRequest_Key {}
}
class_exists(ChangePassphraseRequest\Key::class);
@trigger_error('Walletrpc\ChangePassphraseRequest_Key is deprecated and will be removed in the next major release. Use Walletrpc\ChangePassphraseRequest\Key instead', E_USER_DEPRECATED);

