<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.CreateWalletRequest</code>
 */
class CreateWalletRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     */
    protected $public_passphrase = '';
    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>
     */
    protected $private_passphrase = '';
    /**
     * Generated from protobuf field <code>string mnemonic_seed = 3;</code>
     */
    protected $mnemonic_seed = '';
    /**
     * Generated from protobuf field <code>int64 wallet_birthday = 4;</code>
     */
    protected $wallet_birthday = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $public_passphrase
     *     @type string $private_passphrase
     *     @type string $mnemonic_seed
     *     @type int|string $wallet_birthday
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     * @return string
     */
    public function getPublicPassphrase()
    {
        return $this->public_passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes public_passphrase = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicPassphrase($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>
     * @return string
     */
    public function getPrivatePassphrase()
    {
        return $this->private_passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes private_passphrase = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivatePassphrase($var)
    {
        GPBUtil::checkString($var, False);
        $this->private_passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mnemonic_seed = 3;</code>
     * @return string
     */
    public function getMnemonicSeed()
    {
        return $this->mnemonic_seed;
    }

    /**
     * Generated from protobuf field <code>string mnemonic_seed = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMnemonicSeed($var)
    {
        GPBUtil::checkString($var, True);
        $this->mnemonic_seed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 wallet_birthday = 4;</code>
     * @return int|string
     */
    public function getWalletBirthday()
    {
        return $this->wallet_birthday;
    }

    /**
     * Generated from protobuf field <code>int64 wallet_birthday = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWalletBirthday($var)
    {
        GPBUtil::checkInt64($var);
        $this->wallet_birthday = $var;

        return $this;
    }

}

