<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.CreateTransactionRequest</code>
 */
class CreateTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     */
    protected $account = 0;
    /**
     * Generated from protobuf field <code>repeated .walletrpc.CreateTransactionRequest.Output outputs = 2;</code>
     */
    private $outputs;
    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     */
    protected $required_confirmations = 0;
    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 4;</code>
     */
    protected $sat_per_kb_fee = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $account
     *     @type \Walletrpc\CreateTransactionRequest\Output[]|\Google\Protobuf\Internal\RepeatedField $outputs
     *     @type int $required_confirmations
     *     @type int $sat_per_kb_fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @return int
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.CreateTransactionRequest.Output outputs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.CreateTransactionRequest.Output outputs = 2;</code>
     * @param \Walletrpc\CreateTransactionRequest\Output[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Walletrpc\CreateTransactionRequest\Output::class);
        $this->outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     * @return int
     */
    public function getRequiredConfirmations()
    {
        return $this->required_confirmations;
    }

    /**
     * Generated from protobuf field <code>int32 required_confirmations = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRequiredConfirmations($var)
    {
        GPBUtil::checkInt32($var);
        $this->required_confirmations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 4;</code>
     * @return int
     */
    public function getSatPerKbFee()
    {
        return $this->sat_per_kb_fee;
    }

    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSatPerKbFee($var)
    {
        GPBUtil::checkUint32($var);
        $this->sat_per_kb_fee = $var;

        return $this;
    }

}

