<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\CreateTransactionRequest\Output instead.
     * @deprecated
     */
    class CreateTransactionRequest_Output {}
}
class_exists(CreateTransactionRequest\Output::class);
@trigger_error('Walletrpc\CreateTransactionRequest_Output is deprecated and will be removed in the next major release. Use Walletrpc\CreateTransactionRequest\Output instead', E_USER_DEPRECATED);

