<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.DownloadPaymentRequestResponse</code>
 */
class DownloadPaymentRequestResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string pay_to_name = 1;</code>
     */
    protected $pay_to_name = '';
    /**
     * Generated from protobuf field <code>repeated .walletrpc.DownloadPaymentRequestResponse.Output outputs = 2;</code>
     */
    private $outputs;
    /**
     * Generated from protobuf field <code>int64 expires = 3;</code>
     */
    protected $expires = 0;
    /**
     * Generated from protobuf field <code>string memo = 4;</code>
     */
    protected $memo = '';
    /**
     * Generated from protobuf field <code>string payment_url = 5;</code>
     */
    protected $payment_url = '';
    /**
     * Generated from protobuf field <code>bytes merchant_data = 6;</code>
     */
    protected $merchant_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pay_to_name
     *     @type \Walletrpc\DownloadPaymentRequestResponse\Output[]|\Google\Protobuf\Internal\RepeatedField $outputs
     *     @type int|string $expires
     *     @type string $memo
     *     @type string $payment_url
     *     @type string $merchant_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string pay_to_name = 1;</code>
     * @return string
     */
    public function getPayToName()
    {
        return $this->pay_to_name;
    }

    /**
     * Generated from protobuf field <code>string pay_to_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPayToName($var)
    {
        GPBUtil::checkString($var, True);
        $this->pay_to_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.DownloadPaymentRequestResponse.Output outputs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .walletrpc.DownloadPaymentRequestResponse.Output outputs = 2;</code>
     * @param \Walletrpc\DownloadPaymentRequestResponse\Output[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Walletrpc\DownloadPaymentRequestResponse\Output::class);
        $this->outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expires = 3;</code>
     * @return int|string
     */
    public function getExpires()
    {
        return $this->expires;
    }

    /**
     * Generated from protobuf field <code>int64 expires = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpires($var)
    {
        GPBUtil::checkInt64($var);
        $this->expires = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string memo = 4;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * Generated from protobuf field <code>string memo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payment_url = 5;</code>
     * @return string
     */
    public function getPaymentUrl()
    {
        return $this->payment_url;
    }

    /**
     * Generated from protobuf field <code>string payment_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes merchant_data = 6;</code>
     * @return string
     */
    public function getMerchantData()
    {
        return $this->merchant_data;
    }

    /**
     * Generated from protobuf field <code>bytes merchant_data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantData($var)
    {
        GPBUtil::checkString($var, False);
        $this->merchant_data = $var;

        return $this;
    }

}

