<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\DownloadPaymentRequestResponse\Output instead.
     * @deprecated
     */
    class DownloadPaymentRequestResponse_Output {}
}
class_exists(DownloadPaymentRequestResponse\Output::class);
@trigger_error('Walletrpc\DownloadPaymentRequestResponse_Output is deprecated and will be removed in the next major release. Use Walletrpc\DownloadPaymentRequestResponse\Output instead', E_USER_DEPRECATED);

