<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\FundTransactionResponse\PreviousOutput instead.
     * @deprecated
     */
    class FundTransactionResponse_PreviousOutput {}
}
class_exists(FundTransactionResponse\PreviousOutput::class);
@trigger_error('Walletrpc\FundTransactionResponse_PreviousOutput is deprecated and will be removed in the next major release. Use Walletrpc\FundTransactionResponse\PreviousOutput instead', E_USER_DEPRECATED);

