<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.GenerateMnemonicSeedResponse</code>
 */
class GenerateMnemonicSeedResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mnemonic = 1;</code>
     */
    protected $mnemonic = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mnemonic
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mnemonic = 1;</code>
     * @return string
     */
    public function getMnemonic()
    {
        return $this->mnemonic;
    }

    /**
     * Generated from protobuf field <code>string mnemonic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMnemonic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mnemonic = $var;

        return $this;
    }

}

