<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.ImportPrivateKeyRequest</code>
 */
class ImportPrivateKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>
     */
    protected $passphrase = '';
    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>
     */
    protected $account = 0;
    /**
     * Generated from protobuf field <code>string private_key_wif = 3;</code>
     */
    protected $private_key_wif = '';
    /**
     * Generated from protobuf field <code>bool rescan = 4;</code>
     */
    protected $rescan = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $passphrase
     *     @type int $account
     *     @type string $private_key_wif
     *     @type bool $rescan
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>
     * @return string
     */
    public function getPassphrase()
    {
        return $this->passphrase;
    }

    /**
     * Generated from protobuf field <code>bytes passphrase = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPassphrase($var)
    {
        GPBUtil::checkString($var, False);
        $this->passphrase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>
     * @return int
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key_wif = 3;</code>
     * @return string
     */
    public function getPrivateKeyWif()
    {
        return $this->private_key_wif;
    }

    /**
     * Generated from protobuf field <code>string private_key_wif = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKeyWif($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key_wif = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool rescan = 4;</code>
     * @return bool
     */
    public function getRescan()
    {
        return $this->rescan;
    }

    /**
     * Generated from protobuf field <code>bool rescan = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRescan($var)
    {
        GPBUtil::checkBool($var);
        $this->rescan = $var;

        return $this;
    }

}

