<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.NetworkResponse</code>
 */
class NetworkResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 active_network = 1;</code>
     */
    protected $active_network = 0;
    /**
     * Generated from protobuf field <code>string best_block = 2;</code>
     */
    protected $best_block = '';
    /**
     * Generated from protobuf field <code>int32 best_height = 3;</code>
     */
    protected $best_height = 0;
    /**
     * Generated from protobuf field <code>int32 synced_to = 4;</code>
     */
    protected $synced_to = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $active_network
     *     @type string $best_block
     *     @type int $best_height
     *     @type int $synced_to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 active_network = 1;</code>
     * @return int
     */
    public function getActiveNetwork()
    {
        return $this->active_network;
    }

    /**
     * Generated from protobuf field <code>uint32 active_network = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setActiveNetwork($var)
    {
        GPBUtil::checkUint32($var);
        $this->active_network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string best_block = 2;</code>
     * @return string
     */
    public function getBestBlock()
    {
        return $this->best_block;
    }

    /**
     * Generated from protobuf field <code>string best_block = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBestBlock($var)
    {
        GPBUtil::checkString($var, True);
        $this->best_block = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 best_height = 3;</code>
     * @return int
     */
    public function getBestHeight()
    {
        return $this->best_height;
    }

    /**
     * Generated from protobuf field <code>int32 best_height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBestHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->best_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 synced_to = 4;</code>
     * @return int
     */
    public function getSyncedTo()
    {
        return $this->synced_to;
    }

    /**
     * Generated from protobuf field <code>int32 synced_to = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSyncedTo($var)
    {
        GPBUtil::checkInt32($var);
        $this->synced_to = $var;

        return $this;
    }

}

