<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\NextAddressRequest\Kind instead.
     * @deprecated
     */
    class NextAddressRequest_Kind {}
}
class_exists(NextAddressRequest\Kind::class);
@trigger_error('Walletrpc\NextAddressRequest_Kind is deprecated and will be removed in the next major release. Use Walletrpc\NextAddressRequest\Kind instead', E_USER_DEPRECATED);

