<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\PostPaymentRequest\Output instead.
     * @deprecated
     */
    class PostPaymentRequest_Output {}
}
class_exists(PostPaymentRequest\Output::class);
@trigger_error('Walletrpc\PostPaymentRequest_Output is deprecated and will be removed in the next major release. Use Walletrpc\PostPaymentRequest\Output instead', E_USER_DEPRECATED);

