<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.PostPaymentRequest</code>
 */
class PostPaymentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string payment_url = 1;</code>
     */
    protected $payment_url = '';
    /**
     * Generated from protobuf field <code>bytes merchant_data = 2;</code>
     */
    protected $merchant_data = '';
    /**
     * Generated from protobuf field <code>repeated bytes transactions = 3;</code>
     */
    private $transactions;
    /**
     * Generated from protobuf field <code>.walletrpc.PostPaymentRequest.Output refund_output = 4;</code>
     */
    protected $refund_output = null;
    /**
     * Generated from protobuf field <code>string memo = 5;</code>
     */
    protected $memo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payment_url
     *     @type string $merchant_data
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $transactions
     *     @type \Walletrpc\PostPaymentRequest\Output $refund_output
     *     @type string $memo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string payment_url = 1;</code>
     * @return string
     */
    public function getPaymentUrl()
    {
        return $this->payment_url;
    }

    /**
     * Generated from protobuf field <code>string payment_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->payment_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes merchant_data = 2;</code>
     * @return string
     */
    public function getMerchantData()
    {
        return $this->merchant_data;
    }

    /**
     * Generated from protobuf field <code>bytes merchant_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantData($var)
    {
        GPBUtil::checkString($var, False);
        $this->merchant_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes transactions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated bytes transactions = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.PostPaymentRequest.Output refund_output = 4;</code>
     * @return \Walletrpc\PostPaymentRequest\Output
     */
    public function getRefundOutput()
    {
        return $this->refund_output;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.PostPaymentRequest.Output refund_output = 4;</code>
     * @param \Walletrpc\PostPaymentRequest\Output $var
     * @return $this
     */
    public function setRefundOutput($var)
    {
        GPBUtil::checkMessage($var, \Walletrpc\PostPaymentRequest_Output::class);
        $this->refund_output = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string memo = 5;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * Generated from protobuf field <code>string memo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

}

