<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\SpentnessNotificationsResponse\Spender instead.
     * @deprecated
     */
    class SpentnessNotificationsResponse_Spender {}
}
class_exists(SpentnessNotificationsResponse\Spender::class);
@trigger_error('Walletrpc\SpentnessNotificationsResponse_Spender is deprecated and will be removed in the next major release. Use Walletrpc\SpentnessNotificationsResponse\Spender instead', E_USER_DEPRECATED);

