<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SpentnessNotificationsResponse</code>
 */
class SpentnessNotificationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     */
    protected $transaction_hash = '';
    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     */
    protected $output_index = 0;
    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     */
    protected $spender = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_hash
     *     @type int $output_index
     *     @type \Walletrpc\SpentnessNotificationsResponse\Spender $spender
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     * @return string
     */
    public function getTransactionHash()
    {
        return $this->transaction_hash;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     * @return int
     */
    public function getOutputIndex()
    {
        return $this->output_index;
    }

    /**
     * Generated from protobuf field <code>uint32 output_index = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOutputIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->output_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     * @return \Walletrpc\SpentnessNotificationsResponse\Spender
     */
    public function getSpender()
    {
        return $this->spender;
    }

    /**
     * Generated from protobuf field <code>.walletrpc.SpentnessNotificationsResponse.Spender spender = 3;</code>
     * @param \Walletrpc\SpentnessNotificationsResponse\Spender $var
     * @return $this
     */
    public function setSpender($var)
    {
        GPBUtil::checkMessage($var, \Walletrpc\SpentnessNotificationsResponse_Spender::class);
        $this->spender = $var;

        return $this;
    }

}

