<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SweepAccountResponse</code>
 */
class SweepAccountResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 1;</code>
     */
    protected $serialized_transaction = '';
    /**
     * Generated from protobuf field <code>repeated int64 input_values = 2;</code>
     */
    private $input_values;
    /**
     * Generated from protobuf field <code>int64 total_amount = 3;</code>
     */
    protected $total_amount = 0;
    /**
     * Generated from protobuf field <code>int64 fee = 4;</code>
     */
    protected $fee = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serialized_transaction
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $input_values
     *     @type int|string $total_amount
     *     @type int|string $fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 1;</code>
     * @return string
     */
    public function getSerializedTransaction()
    {
        return $this->serialized_transaction;
    }

    /**
     * Generated from protobuf field <code>bytes serialized_transaction = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSerializedTransaction($var)
    {
        GPBUtil::checkString($var, False);
        $this->serialized_transaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 input_values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputValues()
    {
        return $this->input_values;
    }

    /**
     * Generated from protobuf field <code>repeated int64 input_values = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInputValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->input_values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_amount = 3;</code>
     * @return int|string
     */
    public function getTotalAmount()
    {
        return $this->total_amount;
    }

    /**
     * Generated from protobuf field <code>int64 total_amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 4;</code>
     * @return int|string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee = $var;

        return $this;
    }

}

