<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>walletrpc.SweepAccountRequest</code>
 */
class SweepAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     */
    protected $account = 0;
    /**
     * Generated from protobuf field <code>string sweep_to_address = 2;</code>
     */
    protected $sweep_to_address = '';
    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 3;</code>
     */
    protected $sat_per_kb_fee = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $account
     *     @type string $sweep_to_address
     *     @type int $sat_per_kb_fee
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @return int
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>uint32 account = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkUint32($var);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sweep_to_address = 2;</code>
     * @return string
     */
    public function getSweepToAddress()
    {
        return $this->sweep_to_address;
    }

    /**
     * Generated from protobuf field <code>string sweep_to_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSweepToAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->sweep_to_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 3;</code>
     * @return int
     */
    public function getSatPerKbFee()
    {
        return $this->sat_per_kb_fee;
    }

    /**
     * Generated from protobuf field <code>uint32 sat_per_kb_fee = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSatPerKbFee($var)
    {
        GPBUtil::checkUint32($var);
        $this->sat_per_kb_fee = $var;

        return $this;
    }

}

