<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\TransactionDetails\Output instead.
     * @deprecated
     */
    class TransactionDetails_Output {}
}
class_exists(TransactionDetails\Output::class);
@trigger_error('Walletrpc\TransactionDetails_Output is deprecated and will be removed in the next major release. Use Walletrpc\TransactionDetails\Output instead', E_USER_DEPRECATED);

