<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Walletrpc;

if (false) {
    /**
     * This class is deprecated. Use Walletrpc\TransactionDetails\Input instead.
     * @deprecated
     */
    class TransactionDetails_Input {}
}
class_exists(TransactionDetails\Input::class);
@trigger_error('Walletrpc\TransactionDetails_Input is deprecated and will be removed in the next major release. Use Walletrpc\TransactionDetails\Input instead', E_USER_DEPRECATED);

